version: "3.8"

services:
  linkstack:
    hostname: 'linkstack'
    image: 'linkstackorg/linkstack:latest'
    environment:
      TZ: 'Europe/Berlin'
      SERVER_ADMIN: 'thomas@schouboekoenig.dk'
      HTTPS_SERVER_NAME: 'localhost'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - '/htdocs'
    ports:
      - '4040:4040'
      - '4041:4041'
    exposes:
      - '4040'
      - '4041'
    restart: unless-stopped
    user: apache:apache
    # read_only: true
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:8
    environment:
        MYSQL_ROOT_PASSWORD: xeFgUGb5mPPn5q2d
    ports:
        - 3380:3380